openapi: 3.0.0
info:
  title: PayBeam API
  version: 1.0.0
  description: Full API Docs
contact:
  title: PayBeam Support
  email: hello@getpaybeam.xyz
  url: https://getpaybeam.xyz
paths:
#  AUTH ENDPOINTS
# TODO ADD THE REMAINING AUTH ENDPOINTS
  /api/v1/auth/google:
    get:
      summary: Google OAuth login
      responses:
        200:
          description: Successful login with Google OAuth
# USER ENDPOINTS
# TODO ADD THE REMAINING USER ENDPOINTS
  /api/v1/user/users:
    get:
      summary: Get all users
      responses:
        200:
          description: A list of users
# TODO INVOICE ENDPOINTS
# TODO INVOICE SETTLEMENT ENDPOINTS