version: '3.8'
services:
  db:
    image: postgres:13
    container_name: paybeam_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: paybeam
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: paybeam_app
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: "postgresql://user:password@db:5432/paybeam?schema=public"
    depends_on:
      - db

volumes:
  postgres_data: