services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: paybeam_app
    ports:
      - "5000:3000"
    env_file:
      - .env
    depends_on:
      - db
    command: npm run start
