services:
  db:
    image: postgres:13
    container_name: paybeam_db_dev
    environment:
      POSTGRES_USER: test-user
      POSTGRES_PASSWORD: test-password
      POSTGRES_DB: paybeam
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data

  app:
    container_name: paybeam_app_dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app # Bind mount the entire project directory
      - /app/node_modules # Avoid overwriting node_modules in the container
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: "postgresql://test-user:test-password@db:5432/paybeam?schema=public"
      NODE_ENV: development
    depends_on:
      - db
    command: npm run dev # Use nodemon for hot-reloading

volumes:
  postgres_data_dev:
