services:
  - type: web
    name: paybeam-app
    env: docker
    plan: free
    dockerContext: .
    dockerfilePath: Dockerfile
    buildCommand: npm install
    startCommand: npm run start
    ports:
      - 5000
    dependsOn:
      - name: paybeam-db
    envVars:
      - fromDotEnv: false
